import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import type { ReactNode } from 'react';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { getProvider } from '../../data/providers';

export default function ProviderProfile() {
  const { providerId } = useLocalSearchParams<{ providerId?: string }>();
  const provider = getProvider(String(providerId || ''));
  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><View style={s.bar}><Pressable onPress={() => router.back()} style={s.iconBtn}><Ionicons name="arrow-back" size={23} color="#17382A" /></Pressable><Text style={s.barTitle}>Perfil del prestador</Text><Pressable style={s.iconBtn}><Ionicons name="heart-outline" size={22} color="#276749" /></Pressable></View><View style={s.profile}><View style={s.avatar}><Ionicons name="person" size={38} color="#276749" /></View><View style={s.nameRow}><Text style={s.name}>{provider.name}</Text>{provider.verified && <Ionicons name="checkmark-circle" size={20} color="#58A071" />}</View><Text style={s.service}>{provider.service}</Text><View style={s.rating}><Ionicons name="star" size={16} color="#F2B44B" /><Text style={s.ratingText}>{provider.rating}</Text><Text style={s.light}>({provider.reviews} opiniones)</Text></View></View><View style={s.actions}><Pressable style={s.outline}><Ionicons name="call-outline" size={19} color="#276749" /><Text style={s.outlineText}>Llamar</Text></Pressable><Pressable style={s.primary}><Ionicons name="logo-whatsapp" size={19} color="#FFF" /><Text style={s.primaryText}>WhatsApp</Text></Pressable></View><Section title="Acerca del servicio"><Text style={s.body}>{provider.description}</Text></Section><Section title="Cobertura"><View style={s.chips}>{provider.coverage.map((item) => <View key={item} style={s.chip}><Ionicons name="location-outline" size={14} color="#276749" /><Text style={s.chipText}>{item}</Text></View>)}</View></Section><Section title="Disponibilidad"><View style={s.available}><View style={s.dot} /><Text style={s.availableText}>{provider.available ? 'Disponible para recibir solicitudes' : 'Consultar prÃ³xima disponibilidad'}</Text></View></Section><Pressable onPress={() => router.push({ pathname:'/request-service', params:{ providerId:provider.id, providerName:provider.name, serviceName:provider.service } })} style={s.request}><Text style={s.requestText}>Solicitar servicio</Text><Ionicons name="arrow-forward" size={20} color="#FFF" /></Pressable></ScrollView></SafeAreaView>;
}
function Section({ title, children }:{title:string;children:ReactNode}) { return <View style={s.section}><Text style={s.sectionTitle}>{title}</Text>{children}</View>; }
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#F5F7F2'},content:{width:'100%',maxWidth:720,alignSelf:'center',padding:16,paddingBottom:40},bar:{height:64,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},iconBtn:{width:43,height:43,borderRadius:14,alignItems:'center',justifyContent:'center',backgroundColor:'#FFF',borderWidth:1,borderColor:'#E0E6E1'},barTitle:{fontSize:16,fontWeight:'800',color:'#17382A'},profile:{padding:24,borderRadius:25,alignItems:'center',backgroundColor:'#193E2E'},avatar:{width:80,height:80,borderRadius:25,alignItems:'center',justifyContent:'center',backgroundColor:'#E4EFE7'},nameRow:{flexDirection:'row',alignItems:'center',gap:6,marginTop:15},name:{fontSize:23,fontWeight:'800',color:'#FFF'},service:{marginTop:5,fontSize:13,color:'#C7D5CB'},rating:{flexDirection:'row',alignItems:'center',gap:5,marginTop:12},ratingText:{color:'#FFF',fontWeight:'800'},light:{color:'#BFD0C4',fontSize:11},actions:{flexDirection:'row',gap:10,marginTop:12},outline:{flex:1,height:52,borderRadius:16,flexDirection:'row',gap:7,alignItems:'center',justifyContent:'center',backgroundColor:'#FFF',borderWidth:1,borderColor:'#DDE5DF'},outlineText:{color:'#276749',fontWeight:'800'},primary:{flex:1,height:52,borderRadius:16,flexDirection:'row',gap:7,alignItems:'center',justifyContent:'center',backgroundColor:'#276749'},primaryText:{color:'#FFF',fontWeight:'800'},section:{marginTop:13,padding:18,borderRadius:20,backgroundColor:'#FFF',borderWidth:1,borderColor:'#E0E6E1'},sectionTitle:{fontSize:16,fontWeight:'800',color:'#243D30',marginBottom:10},body:{fontSize:13,lineHeight:20,color:'#68786E'},chips:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{paddingHorizontal:10,paddingVertical:8,borderRadius:11,flexDirection:'row',gap:5,backgroundColor:'#EAF3EC'},chipText:{fontSize:11,fontWeight:'700',color:'#276749'},available:{flexDirection:'row',alignItems:'center',gap:8},dot:{width:8,height:8,borderRadius:4,backgroundColor:'#3C8B5A'},availableText:{fontSize:12,fontWeight:'700',color:'#397550'},request:{height:58,marginTop:14,borderRadius:18,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:9,backgroundColor:'#D17B3F'},requestText:{fontSize:16,fontWeight:'800',color:'#FFF'}});
