import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useMemo, useState } from 'react';
import { FlatList, Pressable, SafeAreaView, StyleSheet, Text, TextInput, View } from 'react-native';
import { PROVIDERS } from '../data/providers';

export default function ProvidersScreen() {
  const params = useLocalSearchParams<{ serviceName?: string; locationName?: string; subcategoryId?: string }>();
  const serviceName = String(params.serviceName || 'Prestadores');
  const locationName = String(params.locationName || 'Lago Ranco');
  const [search, setSearch] = useState('');
  const data = useMemo(() => PROVIDERS.filter((item) => item.name.toLowerCase().includes(search.toLowerCase())), [search]);
  return <SafeAreaView style={s.safe}><FlatList data={data} keyExtractor={(i) => i.id} contentContainerStyle={s.content} ListHeaderComponent={<><View style={s.bar}><Pressable onPress={() => router.back()} style={s.iconBtn}><Ionicons name="arrow-back" size={23} color="#17382A" /></Pressable><View style={s.heading}><Text style={s.barTitle}>{serviceName}</Text><Text style={s.muted}>{locationName}</Text></View><Pressable style={s.iconBtn}><Ionicons name="options-outline" size={21} color="#276749" /></Pressable></View><View style={s.hero}><Text style={s.eyebrow}>PRESTADORES DISPONIBLES</Text><Text style={s.heroTitle}>{serviceName} en {locationName}</Text><Text style={s.heroText}>Compara experiencia, valoraciÃ³n y disponibilidad.</Text></View><View style={s.search}><Ionicons name="search-outline" size={20} color="#718077" /><TextInput value={search} onChangeText={setSearch} placeholder="Buscar prestador" style={s.input} /></View><Text style={s.section}>Resultados</Text></>} renderItem={({ item }) => <Pressable onPress={() => router.push({ pathname: '/provider/[providerId]', params: { providerId: item.id } })} style={s.card}><View style={s.avatar}><Ionicons name="person" size={24} color="#276749" /></View><View style={s.info}><View style={s.nameRow}><Text style={s.name}>{item.name}</Text>{item.verified && <Ionicons name="checkmark-circle" size={17} color="#3B8460" />}</View><Text style={s.muted}>{item.service}</Text><View style={s.meta}><Ionicons name="star" size={14} color="#D78A2F" /><Text style={s.rating}>{item.rating}</Text><Text style={s.muted}>({item.reviews}) Â· {item.distance}</Text></View><Text style={[s.status, !item.available && s.busy]}>{item.available ? 'Disponible' : 'Consultar disponibilidad'}</Text></View><Ionicons name="chevron-forward" size={20} color="#9AA69E" /></Pressable>} /></SafeAreaView>;
}

const s = StyleSheet.create({ safe:{flex:1,backgroundColor:'#F5F7F2'},content:{width:'100%',maxWidth:720,alignSelf:'center',padding:16,paddingBottom:40},bar:{height:64,flexDirection:'row',alignItems:'center'},iconBtn:{width:43,height:43,borderRadius:14,alignItems:'center',justifyContent:'center',backgroundColor:'#FFF',borderWidth:1,borderColor:'#E0E6E1'},heading:{flex:1,alignItems:'center'},barTitle:{color:'#17382A',fontSize:16,fontWeight:'800'},muted:{color:'#718077',fontSize:11,marginTop:2},hero:{padding:22,borderRadius:24,backgroundColor:'#193E2E'},eyebrow:{color:'#BFD3C4',fontSize:10,fontWeight:'800',letterSpacing:1.2},heroTitle:{color:'#FFF',fontSize:27,lineHeight:33,fontWeight:'800',marginTop:8},heroText:{color:'#C7D5CB',fontSize:13,marginTop:7},search:{height:55,marginTop:13,paddingHorizontal:16,borderRadius:17,flexDirection:'row',alignItems:'center',backgroundColor:'#FFF',borderWidth:1,borderColor:'#DEE5DF'},input:{flex:1,marginLeft:10,fontSize:14},section:{fontSize:21,fontWeight:'800',color:'#193A2C',marginTop:25,marginBottom:12},card:{minHeight:125,marginBottom:11,padding:14,borderRadius:20,flexDirection:'row',alignItems:'center',backgroundColor:'#FFF',borderWidth:1,borderColor:'#E0E6E1'},avatar:{width:52,height:52,borderRadius:17,alignItems:'center',justifyContent:'center',backgroundColor:'#E4EFE7'},info:{flex:1,marginLeft:12},nameRow:{flexDirection:'row',alignItems:'center',gap:5},name:{color:'#243D30',fontSize:15,fontWeight:'800'},meta:{flexDirection:'row',alignItems:'center',gap:4,marginTop:7},rating:{fontSize:11,fontWeight:'800',color:'#4A594F'},status:{alignSelf:'flex-start',marginTop:8,paddingHorizontal:8,paddingVertical:5,borderRadius:9,overflow:'hidden',backgroundColor:'#EDF5EF',color:'#397550',fontSize:9,fontWeight:'800'},busy:{backgroundColor:'#F5F1E8',color:'#8A6832'} });
